"""Add column name and price

Revision ID: e1e5b1def0fa
Revises: 08262574bf79
Create Date: 2026-04-16 23:13:41.079610

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1e5b1def0fa'
down_revision: Union[str, Sequence[str], None] = '08262574bf79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('apartments', sa.Column('name', sa.String(), server_default='Уютная квартира', nullable=False))
    op.add_column('apartments', sa.Column('price', sa.Integer(), server_default='1000', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('apartments', 'price')
    op.drop_column('apartments', 'name')
    # ### end Alembic commands ###
