"""Add user profile fields

Revision ID: f8de2dd871cc
Revises: e1e5b1def0fa
Create Date: 2026-04-16 23:56:53.324100

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8de2dd871cc'
down_revision: Union[str, Sequence[str], None] = 'e1e5b1def0fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('full_name', sa.String(), server_default='', nullable=False))
    op.add_column('users', sa.Column('phone', sa.String(), server_default='', nullable=False))
    op.add_column('users', sa.Column('gender', sa.String(), server_default='не указан', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'gender')
    op.drop_column('users', 'phone')
    op.drop_column('users', 'full_name')
    # ### end Alembic commands ###
